export const CAMERA = {
  INITIAL_HEIGHT_OFFSET: 2,
  INITIAL_BACK_DISTANCE: 5,
  TARGET_HEIGHT_OFFSET: 2.5,
  TARGET_BACK_DISTANCE: 5,
  LOOK_AHEAD_DISTANCE: 1,
  LOOK_HEIGHT_OFFSET: 1.5,
  LERP_FACTOR_NORMAL: 0.05,
  LERP_FACTOR_SKATE: 0.03,
};
