export const MOVEMENT = {
  WALKING_VELOCITY: 2,
  RUNNING_VELOCITY: 6,
  JUMP_FORCE: 10,
  JUMP_PREPARATION_TIME: 300,
  JUMP_DURATION: 1800,
};

export const TURNING = {
  NORMAL: 0.03,
  WALKING: 0.05,
  RUNNING: 0.08,
  RUNNING_SLOW: 0.04,
  SKATE: 0.02,
};
